USE [master]
GO

/****** Object:  Database [UHPRESUPUESTO]    Script Date: 25/8/2022 20:47:15 ******/
CREATE DATABASE [UHPRESUPUESTO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UHPRESUPUESTO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MAYRA2\MSSQL\DATA\UHPRESUPUESTO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UHPRESUPUESTO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MAYRA2\MSSQL\DATA\UHPRESUPUESTO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UHPRESUPUESTO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UHPRESUPUESTO] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET ARITHABORT OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [UHPRESUPUESTO] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UHPRESUPUESTO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UHPRESUPUESTO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET  ENABLE_BROKER 
GO

ALTER DATABASE [UHPRESUPUESTO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UHPRESUPUESTO] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UHPRESUPUESTO] SET  MULTI_USER 
GO

ALTER DATABASE [UHPRESUPUESTO] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UHPRESUPUESTO] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UHPRESUPUESTO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UHPRESUPUESTO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UHPRESUPUESTO] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UHPRESUPUESTO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UHPRESUPUESTO] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UHPRESUPUESTO] SET  READ_WRITE 
GO

